/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsPersonalAccessTokenRouteImport } from './routes/docs/personal-access-token'
import { Route as DocsInstallGithubAppRouteImport } from './routes/docs/install-github-app'
import { Route as ApiGithubAppTokenRouteImport } from './routes/api/github-app-token'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPersonalAccessTokenRoute = DocsPersonalAccessTokenRouteImport.update({
  id: '/docs/personal-access-token',
  path: '/docs/personal-access-token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallGithubAppRoute = DocsInstallGithubAppRouteImport.update({
  id: '/docs/install-github-app',
  path: '/docs/install-github-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAppTokenRoute = ApiGithubAppTokenRouteImport.update({
  id: '/api/github-app-token',
  path: '/api/github-app-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/github-app-token': typeof ApiGithubAppTokenRoute
  '/docs/install-github-app': typeof DocsInstallGithubAppRoute
  '/docs/personal-access-token': typeof DocsPersonalAccessTokenRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/github-app-token': typeof ApiGithubAppTokenRoute
  '/docs/install-github-app': typeof DocsInstallGithubAppRoute
  '/docs/personal-access-token': typeof DocsPersonalAccessTokenRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/github-app-token': typeof ApiGithubAppTokenRoute
  '/docs/install-github-app': typeof DocsInstallGithubAppRoute
  '/docs/personal-access-token': typeof DocsPersonalAccessTokenRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/github-app-token'
    | '/docs/install-github-app'
    | '/docs/personal-access-token'
    | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/github-app-token'
    | '/docs/install-github-app'
    | '/docs/personal-access-token'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/github-app-token'
    | '/docs/install-github-app'
    | '/docs/personal-access-token'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiGithubAppTokenRoute: typeof ApiGithubAppTokenRoute
  DocsInstallGithubAppRoute: typeof DocsInstallGithubAppRoute
  DocsPersonalAccessTokenRoute: typeof DocsPersonalAccessTokenRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/personal-access-token': {
      id: '/docs/personal-access-token'
      path: '/docs/personal-access-token'
      fullPath: '/docs/personal-access-token'
      preLoaderRoute: typeof DocsPersonalAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/install-github-app': {
      id: '/docs/install-github-app'
      path: '/docs/install-github-app'
      fullPath: '/docs/install-github-app'
      preLoaderRoute: typeof DocsInstallGithubAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-app-token': {
      id: '/api/github-app-token'
      path: '/api/github-app-token'
      fullPath: '/api/github-app-token'
      preLoaderRoute: typeof ApiGithubAppTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiGithubAppTokenRoute: ApiGithubAppTokenRoute,
  DocsInstallGithubAppRoute: DocsInstallGithubAppRoute,
  DocsPersonalAccessTokenRoute: DocsPersonalAccessTokenRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
